{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "plugin",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cg5buhap75crfki25f2oyi2twa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.12.jar",
          "url": "plugin-0.12.jar",
          "size": 89510,
          "sha512": "80861f03ae3b5fca384bc646bd25ca52b818e873ba21925cc341bb377b68120436867fc96842d06348cc78cac55cb5e3fb25392bb8f54e8660f97aee2b9ceb2a",
          "sha256": "06878cc7e89eae743f3ecc78b3677ee23715ac6198e3fb64e138b8a577cffa4f",
          "sha1": "9bfbb520153ed57752ebba41c030154c5e094d90",
          "md5": "0516b823e5b49a2f7bdc745a87e3c7ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.12.jar",
          "url": "plugin-0.12.jar",
          "size": 89510,
          "sha512": "80861f03ae3b5fca384bc646bd25ca52b818e873ba21925cc341bb377b68120436867fc96842d06348cc78cac55cb5e3fb25392bb8f54e8660f97aee2b9ceb2a",
          "sha256": "06878cc7e89eae743f3ecc78b3677ee23715ac6198e3fb64e138b8a577cffa4f",
          "sha1": "9bfbb520153ed57752ebba41c030154c5e094d90",
          "md5": "0516b823e5b49a2f7bdc745a87e3c7ae"
        }
      ]
    }
  ]
}
