{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "plugin",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "aszibp6xljdipc7vrflsulctzi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.12.jar",
          "url": "plugin-0.12.jar",
          "size": 93702,
          "sha512": "34252321cb5bfb6bf5bbfa5a6a8e7fb8f22c70dbb054a398812383b8427fec3429bb0d846d3283b5281f6954f887a716911bfad975a3ebbe21f06a08a870bb21",
          "sha256": "0fb22c348e07b787924c06107ff29fad1c4be7db0ec55b1cf79d063c65cae1a6",
          "sha1": "6cd3a5c1a2091b218fdc3e0194f219c956ff66a4",
          "md5": "01befb0c97d584f07665bb005c7c11f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.12.jar",
          "url": "plugin-0.12.jar",
          "size": 93702,
          "sha512": "34252321cb5bfb6bf5bbfa5a6a8e7fb8f22c70dbb054a398812383b8427fec3429bb0d846d3283b5281f6954f887a716911bfad975a3ebbe21f06a08a870bb21",
          "sha256": "0fb22c348e07b787924c06107ff29fad1c4be7db0ec55b1cf79d063c65cae1a6",
          "sha1": "6cd3a5c1a2091b218fdc3e0194f219c956ff66a4",
          "md5": "01befb0c97d584f07665bb005c7c11f4"
        }
      ]
    }
  ]
}
