{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "plugin",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lelit4zlwrcczb5jowtquhxaia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.12.jar",
          "url": "plugin-0.12.jar",
          "size": 91900,
          "sha512": "fc9a2a11a206247c01aa10ecd5b1e7665fa0fae302468f5ef06ccfcd15e9269fa35d3904a23181a4ee7650bf6668bc34f73203b1828eecc11500e58582a7d548",
          "sha256": "cdda8c6397636c5910be281646abaff835521078edcadab7104419ea63ec1902",
          "sha1": "be45148c09e1b73c8d29686c63ecbee2b0657d7e",
          "md5": "924a228d975b69730bf3354ab7ac991b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.12.jar",
          "url": "plugin-0.12.jar",
          "size": 91900,
          "sha512": "fc9a2a11a206247c01aa10ecd5b1e7665fa0fae302468f5ef06ccfcd15e9269fa35d3904a23181a4ee7650bf6668bc34f73203b1828eecc11500e58582a7d548",
          "sha256": "cdda8c6397636c5910be281646abaff835521078edcadab7104419ea63ec1902",
          "sha1": "be45148c09e1b73c8d29686c63ecbee2b0657d7e",
          "md5": "924a228d975b69730bf3354ab7ac991b"
        }
      ]
    }
  ]
}
