{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "core",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cfrizijbhjhira7gtgto3ezogu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-0.12.jar",
          "url": "core-0.12.jar",
          "size": 89247,
          "sha512": "6a61353cc8b9e040bcba9623247cd956ca263ba43b03f5bbb4e1e4aeb599eaa96b1c0a727f37eefb1be980182c83a1d41845b69f472def8f620d9870adadaa14",
          "sha256": "a098f5aa60178aaf8ce4da3f3eecc773665358f676f9fb1adf19f549802e72ae",
          "sha1": "bdabbc2820b817f6ac20fca4111cddbc4d0c25d2",
          "md5": "2eb15aa53f9d294583d7bbe8a51a1c85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.12.jar",
          "url": "core-0.12.jar",
          "size": 89247,
          "sha512": "6a61353cc8b9e040bcba9623247cd956ca263ba43b03f5bbb4e1e4aeb599eaa96b1c0a727f37eefb1be980182c83a1d41845b69f472def8f620d9870adadaa14",
          "sha256": "a098f5aa60178aaf8ce4da3f3eecc773665358f676f9fb1adf19f549802e72ae",
          "sha1": "bdabbc2820b817f6ac20fca4111cddbc4d0c25d2",
          "md5": "2eb15aa53f9d294583d7bbe8a51a1c85"
        }
      ]
    }
  ]
}
