{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "core",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ctt7zriisbd2lpc6w72stu5p5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-0.12.jar",
          "url": "core-0.12.jar",
          "size": 88782,
          "sha512": "48e116cf263dbdd2a0f5c6d2bb369634034efc48f4e9d707703f6bd8e7973f9288966b1a261bccdce09ad7faf2166641a741a57191642b706922d2622cf11891",
          "sha256": "0ea485d451f0052f4caceaab4cba007d2eb30af70ca92662312e536a8b918205",
          "sha1": "907a4fbaa111cb3cc5d9390c4585407e2ef2be96",
          "md5": "236703727a46ccbdfcf49a28d6fd79a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.12.jar",
          "url": "core-0.12.jar",
          "size": 88782,
          "sha512": "48e116cf263dbdd2a0f5c6d2bb369634034efc48f4e9d707703f6bd8e7973f9288966b1a261bccdce09ad7faf2166641a741a57191642b706922d2622cf11891",
          "sha256": "0ea485d451f0052f4caceaab4cba007d2eb30af70ca92662312e536a8b918205",
          "sha1": "907a4fbaa111cb3cc5d9390c4585407e2ef2be96",
          "md5": "236703727a46ccbdfcf49a28d6fd79a1"
        }
      ]
    }
  ]
}
