{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "core",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wgndhpibqnhvhgyfzvvbitthii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-0.12.jar",
          "url": "core-0.12.jar",
          "size": 89247,
          "sha512": "2a876e92a29c7ca03fdacd16935dec1bdc0bca6bd369db68981c86691fe6e42857f01fd6efad3fe14a57ac5226119cf616fd627bdac4fcfe667e09abe2f736f1",
          "sha256": "74bb616755b6be8cc22610c860233f3f0ad820aaba41354bb9c55002466ae324",
          "sha1": "057b44181542d9289eda5fc598a180ec9262c212",
          "md5": "3f1aebf386e1e8a69b18754f50287796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.12.jar",
          "url": "core-0.12.jar",
          "size": 89247,
          "sha512": "2a876e92a29c7ca03fdacd16935dec1bdc0bca6bd369db68981c86691fe6e42857f01fd6efad3fe14a57ac5226119cf616fd627bdac4fcfe667e09abe2f736f1",
          "sha256": "74bb616755b6be8cc22610c860233f3f0ad820aaba41354bb9c55002466ae324",
          "sha1": "057b44181542d9289eda5fc598a180ec9262c212",
          "md5": "3f1aebf386e1e8a69b18754f50287796"
        }
      ]
    }
  ]
}
