{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "plugin",
    "version": "0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3tkvixilljhvdjo35cpatn25ai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.13.jar",
          "url": "plugin-0.13.jar",
          "size": 95424,
          "sha512": "9a6e11bd14f20f609e2c4fddc3445f3a86389407f8792898ae0c47d17df56062fc4eac04dd70fce1c6da55c0a6c0908e1a22ffe4151c31b456d763bcf0e97835",
          "sha256": "74bf5c77bbe935d34955a62af4ed000c23e09d922e7e7a2cfebf49b2314851b5",
          "sha1": "a1120b781bbde6eb22f0976a8aa45b8c5b8dfd75",
          "md5": "54c5a08871e7b127c118c26c6075fc51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.13.jar",
          "url": "plugin-0.13.jar",
          "size": 95424,
          "sha512": "9a6e11bd14f20f609e2c4fddc3445f3a86389407f8792898ae0c47d17df56062fc4eac04dd70fce1c6da55c0a6c0908e1a22ffe4151c31b456d763bcf0e97835",
          "sha256": "74bf5c77bbe935d34955a62af4ed000c23e09d922e7e7a2cfebf49b2314851b5",
          "sha1": "a1120b781bbde6eb22f0976a8aa45b8c5b8dfd75",
          "md5": "54c5a08871e7b127c118c26c6075fc51"
        }
      ]
    }
  ]
}
