{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pablisco.gradle.automodule",
    "module": "plugin",
    "version": "0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "q23zt62w3nelxa7wpaswnhosnm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.15.jar",
          "url": "plugin-0.15.jar",
          "size": 136271,
          "sha512": "af9e87297acee21ead635a1d5f7f2cf6fd38a936e6f35f78376c6c89c86bc8e9f30ffd702522a3a7df87c72a945b33c6c2c3a4e33c3a307051cd3594b5836045",
          "sha256": "545bdbd9c5ce22e2d0bac0e6ba03cad8e0dfc6eb165d3a9646f1cbc78e6d1270",
          "sha1": "5f778159293ec3d7189ee71b57fcacba44b8fb6c",
          "md5": "850a3c198302ac7747ee1d9ddd3a5280"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.15.jar",
          "url": "plugin-0.15.jar",
          "size": 136271,
          "sha512": "af9e87297acee21ead635a1d5f7f2cf6fd38a936e6f35f78376c6c89c86bc8e9f30ffd702522a3a7df87c72a945b33c6c2c3a4e33c3a307051cd3594b5836045",
          "sha256": "545bdbd9c5ce22e2d0bac0e6ba03cad8e0dfc6eb165d3a9646f1cbc78e6d1270",
          "sha1": "5f778159293ec3d7189ee71b57fcacba44b8fb6c",
          "md5": "850a3c198302ac7747ee1d9ddd3a5280"
        }
      ]
    }
  ]
}
